# Generated by Django 5.1.2 on 2024-11-02 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='craeted_at',
            new_name='created_at',
        ),
    ]
